parameters:
  - name: release
    displayName: Create GitHub Release
    type: boolean
    default: false

trigger:
  branches:
    include:
      - main

pr:
- main

name: $(Build.BuildId)

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool: 1es-windows-2022-x64
      componentgovernance:
        ignoreDirectories: 'deps,out,node-gyp'
      armory:
        enabled: false # No ARM deployment files in this repository
      createAdoIssuesForJustificationsForDisablement: false
      tsa:
        enabled: false

    stages:
      - stage: Windows
        jobs:
          - job: build_x64
            displayName: Build (x64)
            pool:
              name: 1es-windows-2022-x64
              os: windows
            variables:
              arch: x64
            steps:
              - template: ci/build-win32.yml@self

          - job: build_arm64
            displayName: Build (ARM64)
            pool:
              name: 1es-windows-2022-x64
              os: windows
            variables:
              arch: arm64
            steps:
              - template: ci/build-win32.yml@self

      - ${{ if parameters.release }}:
        - stage: Release
          dependsOn: Windows
          pool:
            name: 1es-ubuntu-22.04-x64
            os: linux
          jobs:
            - job: release
              templateContext:
                type: releaseJob
                isProduction: true
                inputs:
                  - input: pipelineArtifact
                    artifactName: win-x64
                    targetPath: $(Pipeline.Workspace)/win-x64
                  - input: pipelineArtifact
                    artifactName: win-arm64
                    targetPath: $(Pipeline.Workspace)/win-arm64
                  - input: pipelineArtifact
                    artifactName: win-x64-insider
                    targetPath: $(Pipeline.Workspace)/win-x64-insider
                  - input: pipelineArtifact
                    artifactName: win-arm64-insider
                    targetPath: $(Pipeline.Workspace)/win-arm64-insider
              steps:
                - script: cp $(Pipeline.Workspace)/win-x64/code_explorer_command.dll $(Build.ArtifactStagingDirectory)/code_explorer_command_x64.dll
                  displayName: Windows x64
                - script: cp $(Pipeline.Workspace)/win-arm64/code_explorer_command.dll $(Build.ArtifactStagingDirectory)/code_explorer_command_arm64.dll
                  displayName: Windows arm64
                - script: cp $(Pipeline.Workspace)/win-x64-insider/code_insider_explorer_command.dll $(Build.ArtifactStagingDirectory)/code_insider_explorer_command_x64.dll
                  displayName: Windows x64 Insider
                - script: cp $(Pipeline.Workspace)/win-arm64-insider/code_insider_explorer_command.dll $(Build.ArtifactStagingDirectory)/code_insider_explorer_command_arm64.dll
                  displayName: Windows arm64 Insider
                - script: (cd $(Build.ArtifactStagingDirectory) ; shasum -a 256 *.dll) > $(Build.ArtifactStagingDirectory)/SHASUMS256.txt
                  displayName: Compute checksums
                - script: |
                    mkdir -p $(Build.SourcesDirectory)/noop
                  displayName: Create empty directory
                - task: ComponentGovernanceComponentDetection@0
                  inputs:
                    sourceScanPath: $(Build.SourcesDirectory)/noop
                - task: GithubRelease@1
                  displayName: Create GitHub Release
                  inputs:
                    gitHubConnection: oauth
                    repositoryName: microsoft/vscode-explorer-command
                    assets: |
                      $(Build.ArtifactStagingDirectory)/*.dll
                      $(Build.ArtifactStagingDirectory)/SHASUMS256.txt
                    action: create
                    addChangeLog: false
                    tagSource: userSpecifiedTag
                    tag: v4.0.0-$(Build.BuildNumber)
